// swift-tools-version: 6.0
import PackageDescription

// Generated by platforms/swift/mirror.sh in colyseus/native-sdk — edit it there.
//
// The core is Zig as much as it is C — msgpack, http and the certificate store
// are Zig modules — so SwiftPM cannot compile it from source. It arrives as a
// pre-built xcframework, pinned here to the release this tag was cut from.

let package = Package(
    name: "Colyseus",
    platforms: [
        .macOS(.v13),
        .iOS(.v15),
        .tvOS(.v15),
    ],
    products: [
        .library(name: "Colyseus", targets: ["Colyseus"]),
    ],
    targets: [
        .target(
            name: "Colyseus",
            dependencies: ["CColyseus"],
            path: "Sources/Colyseus",
            swiftSettings: [.swiftLanguageMode(.v6)],
            linkerSettings: [
                // A static library in an xcframework carries no dependency
                // information, so the frameworks the core reaches for — the
                // keychain, the system certificate store — are linked here.
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
            ]
        ),
        .binaryTarget(
            name: "CColyseus",
            url: "https://github.com/colyseus/native-sdk/releases/download/v0.18.4/Colyseus.xcframework.zip",
            checksum: "afb4f0b9a026cc1c95e155e80125c955bbdc1d5b3f59f82e750882f2f6c2f342"
        ),
        .testTarget(
            name: "ColyseusTests",
            dependencies: ["Colyseus", "CColyseus"],
            path: "Tests/ColyseusTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
